package com.chrisnewland.jitwatch.mcp;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import com.chrisnewland.jitwatch.mcp.answer.Answer;
import com.chrisnewland.jitwatch.mcp.answer.Budget;
import com.chrisnewland.jitwatch.mcp.session.SessionStore;
import com.chrisnewland.jitwatch.mcp.tools.CheckupTool;
import com.chrisnewland.jitwatch.mcp.tools.DeoptsTool;
import com.chrisnewland.jitwatch.mcp.tools.ExplainCallSiteTool;
import com.chrisnewland.jitwatch.mcp.tools.ExplainMethodTool;
import com.chrisnewland.jitwatch.mcp.tools.FindMethodsTool;
import com.chrisnewland.jitwatch.mcp.tools.InliningTreeTool;
import com.chrisnewland.jitwatch.mcp.tools.LoadLogTool;
import com.chrisnewland.jitwatch.mcp.tools.ToolContext;
import com.chrisnewland.jitwatch.mcp.tools.TopListTool;

/**
 * Drives every tool against a real HotSpot log produced by a program written to provoke
 * known JIT behaviour, and asserts the answers say what the compiler actually did.
 *
 * The fixture is generated by src/test/resources/make-fixture.sh, which compiles and runs
 * JitDemo.java with -XX:+LogCompilation. The test skips rather than fails when the
 * fixture is absent, so a fresh clone builds without needing a JVM run first.
 */
class GoldenLogTest {

	private static Path fixtureDir;

	private static LoadLogTool loadLog;

	private static CheckupTool checkup;

	private static FindMethodsTool findMethods;

	private static ExplainMethodTool explainMethod;

	private static ExplainCallSiteTool explainCallSite;

	private static InliningTreeTool inliningTree;

	private static TopListTool topList;

	private static DeoptsTool deopts;

	private static String sessionId;

	@BeforeAll
	static void loadFixture() throws Exception {
		fixtureDir = Fixture.build();

		Assumptions.assumeTrue(fixtureDir != null,
				"could not produce a compilation log on this JDK; the tests need a JDK that can compile and run a program");

		ToolContext context = new ToolContext(new SessionStore(2), Budget.defaults(), List.of());

		loadLog = new LoadLogTool(context);
		checkup = new CheckupTool(context);
		findMethods = new FindMethodsTool(context);
		explainMethod = new ExplainMethodTool(context);
		explainCallSite = new ExplainCallSiteTool(context);
		inliningTree = new InliningTreeTool(context);
		topList = new TopListTool(context);
		deopts = new DeoptsTool(context);

		Answer loaded = loadLog.load(fixtureDir.resolve("hotspot.log").toString(),
				List.of(fixtureDir.resolve("src").toString()), List.of(fixtureDir.resolve("classes").toString()),
				"hotspot");

		sessionId = (String) loaded.getEvidence().get("session_id");

		assertNotNull(sessionId, "load_log must return a session id");
	}

	@Test
	void loadLogReportsTheRunAndTheFlagsThatApplied() throws Exception {
		Answer answer = loadLog.load(fixtureDir.resolve("hotspot.log").toString(), List.of(), List.of(), null);

		Map<String, Object> counts = asMap(answer.getEvidence().get("counts"));

		assertTrue(((Number) counts.get("compilations")).intValue() > 10, "the demo produces many compilations");
		assertTrue(((Number) counts.get("c2")).intValue() > 0, "C2 compiled something");

		Map<String, Object> flags = asMap(answer.getEvidence().get("flags_in_effect"));

		Map<String, Object> freqInlineSize = asMap(flags.get("FreqInlineSize"));

		assertEquals(325L, ((Number) freqInlineSize.get("value")).longValue(),
				"FreqInlineSize default must be reported so a refusal can be explained against it");
	}

	@Test
	void checkupFindsTheOversizedHotCallee() throws Exception {
		Answer answer = checkup.checkup(sessionId, "demo", 10);

		List<?> findings = (List<?>) answer.getEvidence().get("findings");

		assertFalse(findings.isEmpty(), "the demo deliberately contains an un-inlinable hot method");

		boolean foundBig = false;

		for (Object raw : findings) {
			Map<String, Object> finding = asMap(raw);

			if (!"HOT_METHOD_TOO_LARGE".equals(finding.get("type"))) {
				continue;
			}

			Map<String, Object> evidence = asMap(finding.get("evidence"));

			String callee = String.valueOf(evidence.get("callee"));

			if (!callee.contains("big")) {
				continue;
			}

			foundBig = true;

			assertEquals("FreqInlineSize", evidence.get("flag"), "C2's refusal is against FreqInlineSize");
			assertEquals(325L, ((Number) evidence.get("limit")).longValue());
			assertTrue(((Number) evidence.get("actual")).longValue() > 325,
					"the callee must be reported as larger than the limit");

			assertNotNull(finding.get("fix"), "a finding must say what to try");
			assertTrue(String.valueOf(finding.get("plain")).length() > 40,
					"plain text must be a sentence, not a label");
		}

		assertTrue(foundBig, "checkup must surface the hot method that is too large to inline");
	}

	@Test
	void checkupLeadsWithTheActionableFinding() throws Exception {
		Answer answer = checkup.checkup(sessionId, "demo", 10);

		List<?> findings = (List<?>) answer.getEvidence().get("findings");

		Map<String, Object> first = asMap(findings.get(0));

		assertEquals("HOT_METHOD_TOO_LARGE", first.get("type"), "the planted problem must lead, not warm-up noise");

		Map<String, Object> where = asMap(first.get("where"));

		assertNotNull(where.get("line"), "a finding must point at a source line when classes are mounted");
	}

	@Test
	void findingsNeverReportAMethodCountAsACallSiteCount() throws Exception {
		Answer answer = checkup.checkup(sessionId, null, 25);

		for (Object raw : (List<?>) answer.getEvidence().get("findings")) {
			Map<String, Object> finding = asMap(raw);

			// Counting the caller's own invocations as if they happened at one call site
			// would
			// overstate a finding by orders of magnitude, so the two keys are never both
			// present
			assertFalse(finding.containsKey("calls_at_this_site") && finding.containsKey("method_invocations"),
					"a finding reports one kind of count, never both");
		}
	}

	@Test
	void findingsAboutTheJdkDoNotTellTheReaderToEditIt() throws Exception {
		Answer answer = checkup.checkup(sessionId, null, 25);

		for (Object raw : (List<?>) answer.getEvidence().get("findings")) {
			Map<String, Object> finding = asMap(raw);

			if (!Boolean.TRUE.equals(finding.get("in_platform_code"))) {
				continue;
			}

			assertEquals("info", finding.get("severity"), "a finding the reader cannot act on must not lead the list");

			assertFalse(String.valueOf(finding.get("fix")).startsWith("Split "), "never advise splitting a JDK method");
		}
	}

	@Test
	void checkupPrefersTheVerdictOfTheCompilerThatMatters() throws Exception {
		Answer answer = checkup.checkup(sessionId, "demo", 25);

		for (Object raw : (List<?>) answer.getEvidence().get("findings")) {
			Map<String, Object> finding = asMap(raw);

			if (!"HOT_METHOD_TOO_LARGE".equals(finding.get("type"))) {
				continue;
			}

			Map<String, Object> evidence = asMap(finding.get("evidence"));

			String callee = String.valueOf(evidence.get("callee"));

			if (callee.contains("JitDemo.big")) {
				// C1 refuses the same call against MaxInlineSize=35, which describes
				// warm-up.
				// The finding must carry C2's verdict, which describes the code that
				// runs.
				assertEquals("C2", evidence.get("compiler"));
				assertEquals("FreqInlineSize", evidence.get("flag"));
			}
		}
	}

	@Test
	void explainCallSiteCarriesTheLimitThatApplied() throws Exception {
		Answer answer = explainCallSite.explainCallSite(sessionId, "JitDemo.main", null, 25);

		List<?> decisions = (List<?>) answer.getEvidence().get("decisions");

		assertFalse(decisions.isEmpty(), "bytecode 25 in main is the call to big()");

		boolean sawC2Refusal = false;

		for (Object raw : decisions) {
			Map<String, Object> decision = asMap(raw);

			// compiler must be C1 or C2 alone; whether it was on-stack replacement is a
			// separate flag
			assertTrue("C1".equals(decision.get("compiler")) || "C2".equals(decision.get("compiler")),
					"compiler must be C1 or C2, was " + decision.get("compiler"));

			if ("C2".equals(decision.get("compiler")) && "NOT_INLINED".equals(decision.get("outcome"))) {
				sawC2Refusal = true;

				assertEquals("CALLEE_TOO_LARGE", decision.get("reason_normalised"));
				assertEquals("hot method too big", decision.get("reason"), "the raw HotSpot wording must survive");
				assertEquals(325L, ((Number) decision.get("limit")).longValue());
			}
		}

		assertTrue(sawC2Refusal, "C2 refuses to inline big() into main()");

		assertTrue(answer.getPlain().contains("NOT inlined"), "the plain half must state the outcome");
	}

	@Test
	void explainMethodCarriesSourceLinesWhenClassesAreMounted() throws Exception {
		Answer answer = explainMethod.explainMethod(sessionId, "JitDemo.main");

		boolean anyLine = false;

		for (Object raw : (List<?>) answer.getEvidence().get("call_sites")) {
			if (asMap(raw).get("line") != null) {
				anyLine = true;
				break;
			}
		}

		assertTrue(anyLine, "mounted classes compiled with -g must yield source line numbers");
	}

	@Test
	void explainMethodDescribesCompilationsAndCallSites() throws Exception {
		Answer answer = explainMethod.explainMethod(sessionId, "JitDemo.main");

		List<?> compilations = (List<?>) answer.getEvidence().get("compilations");

		assertFalse(compilations.isEmpty());

		List<?> callSites = (List<?>) answer.getEvidence().get("call_sites");

		assertFalse(callSites.isEmpty(), "main calls add() and big() in a loop");

		assertTrue(answer.getPlain().contains("bytes of bytecode"), "plain half must describe the method's size");
	}

	@Test
	void inliningTreeShowsWhatWasFoldedIn() throws Exception {
		Answer answer = inliningTree.inliningTree(sessionId, "JitDemo.main", null, 6);

		Map<String, Object> tree = asMap(answer.getEvidence().get("tree"));

		assertNotNull(tree.get("callee"));

		List<?> children = (List<?>) tree.get("children");

		assertNotNull(children, "main inlines at least one callee");
		assertFalse(children.isEmpty());

		// The tree must distinguish what became part of the caller from what stayed a
		// real call.
		// Both appear somewhere in the demo's tree, not necessarily at the top level.
		boolean[] seen = new boolean[2];

		walk(tree, seen);

		assertTrue(seen[0], "some callee was inlined");
		assertTrue(seen[1], "some callee was not inlined, and the tree must show that");
	}

	private static void walk(Map<String, Object> node, boolean[] seen) {
		Object inlined = node.get("inlined");

		if (Boolean.TRUE.equals(inlined)) {
			seen[0] = true;
		}
		else if (Boolean.FALSE.equals(inlined)) {
			seen[1] = true;
		}

		assertNotNull(node.get("callee"), "every node must name its callee, even an unknown virtual target");

		Object children = node.get("children");

		if (children instanceof List<?> list) {
			for (Object child : list) {
				walk(asMap(child), seen);
			}
		}
	}

	@Test
	void findMethodsResolvesAPartialName() throws Exception {
		Answer answer = findMethods.findMethods(sessionId, "sumOfPoint", true, 10);

		List<?> matches = (List<?>) answer.getEvidence().get("matches");

		assertFalse(matches.isEmpty());

		assertTrue(String.valueOf(asMap(matches.get(0)).get("signature")).contains("sumOfPoint"));
	}

	@Test
	void topListRanksInliningFailureReasons() throws Exception {
		Answer answer = topList.topList(sessionId, "inline_fail_reasons", 10);

		List<?> rows = (List<?>) answer.getEvidence().get("rows");

		assertFalse(rows.isEmpty(), "the demo produces inlining failures");
	}

	@Test
	void deoptsFindTheMethodThatWasThrownAway() throws Exception {
		Answer answer = deopts.deopts(sessionId, null, 10);

		List<?> rows = (List<?>) answer.getEvidence().get("deoptimised_methods");

		assertFalse(rows.isEmpty(), "branchy() is written to deoptimise");
	}

	@Test
	void everyAnswerHasBothHalves() throws Exception {
		Answer answer = checkup.checkup(sessionId, null, 5);

		Map<String, Object> map = answer.toMap();

		assertTrue(map.containsKey("plain"), "the plain half is mandatory");
		assertTrue(map.containsKey("evidence"), "the evidence half is mandatory");
		assertFalse(String.valueOf(map.get("plain")).isBlank());
	}

	@Test
	void unknownSessionFailsWithAUsefulMessage() {
		Exception thrown = org.junit.jupiter.api.Assertions.assertThrows(Exception.class,
				() -> checkup.checkup("nope", null, 5));

		assertTrue(thrown.getMessage().contains("Unknown session"));
	}

	@SuppressWarnings("unchecked")
	private static Map<String, Object> asMap(Object value) {
		assertNotNull(value, "expected a map, got null");
		return (Map<String, Object>) value;
	}

}
